### ISSUE TITLE
Cloudflare pages deploy results in 404 status when index page is "static"

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/waku#869]
Repro:

```bash
npm create waku@0.9.3
cd waku-project
npm install
npm run build -- --with-cloudflare
npx wrangler pages dev
```

<img width="738" alt="image" src="https://github.com/user-attachments/assets/58e67b4f-186c-482c-a79b-760b04e03b7d">

It's the same when it's deployed with `npx wrangler pages deploy`.

@jkhaui @rmarscher

**Comment by rmarscher** [comment]
This is a good catch. At first, I thought I only needed to fix the root index route, but now I see more work needs to be done on cloudflare static routing to avoid more bugs.

**Comment by dai-shi** [comment]
A page will be static when the page itself and all parent layouts are static, AFAIR. This is how it works and we may change something in the future.
For the current behavior @tylerlaws0n might be able to help clarifying.

**Comment by rmarscher** [comment]
I found that astro has done a lot of work to generate cloudflare's _routes.json file. I'd like to see if we can do something similar in #870 

https://github.com/withastro/adapters/tree/main/packages/cloudflare

Specifically - https://github.com/withastro/adapters/blob/main/packages/cloudflare/src/utils/generate-routes-json.ts

**Comment by rmarscher** [comment]
I submitted a fix. It was pretty easy to just continue to walk the public build dir and add an html files as static routes.

After rebasing, I found a much bigger error with cloudflare not being able to run dynamic routes due to attempting to import node:fs. See my comment in the PR here - https://github.com/dai-shi/waku/pull/870#issuecomment-2342303370
