### ISSUE TITLE
Bug: [DEV only] waku app with vanilla-extract

### ISSUE THREAD

**Issue by ojj1123** [dai-shi/waku#953]
## Background

I was migrating waku app into `waku@0.21.3` with `vanilla-extract`. I encountered this error:

```shell
> waku dev

ready: Listening on http://localhost:3000/
Cannot process SSR ReferenceError: __vanilla_globalCssAdapter__ is not defined
    at eval (/Users/jeongjin/GitHub/waku-vanilla/src/components/styles.css.ts:7:34)
    at async instantiateModule (file:///Users/jeongjin/GitHub/waku-vanilla/node_modules/.pnpm/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5) {
  plugin: 'rsc-delegate-plugin',
  id: '/Users/jeongjin/GitHub/waku-vanilla/src/pages/index.tsx',
  pluginCode: 'import { jsxDEV } from "react/jsx-dev-runtime";\n' +
    'import { Link } from "waku";\n' +
    'import { Counter } from "../components/counter";\n' +
    'import { container } from "../components/styles.css";\n' +
    'export default async function HomePage() {\n' +
    '  const data = await getData();\n' +
    '  return /* @__PURE__ */ jsxDEV("div", { className: container, children: [\n' +
...
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReferenceError: __vanilla_globalCssAdapter__ is not defined
    at eval (/Users/jeongjin/GitHub/waku-vanilla/src/components/styles.css.ts:7:34)
    at async instantiateModule (file:///Users/jeongjin/GitHub/waku-vanilla/node_modules/.pnpm/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5) {
  plugin: 'rsc-delegate-plugin',
  id: '/Users/jeongjin/GitHub/waku-vanilla/src/pages/index.tsx',
  pluginCode: 'import { jsxDEV } from "react/jsx-dev-runtime";\n' +
    'import { Link } from "waku";\n' +
    'import { Counter } from "../components/counter";\n' +
    'import { container } from "../components/styles.css";\n' +
    'export default async function HomePage() {\n' +
    '  const data = await getData();\n' +
    '  return /* @__PURE__ */ jsxDEV("div", { className: container, children: [\n' +
...
}
```

## How to reproduce

This is reproduction of this issue.
https://github.com/ojj1123/repro-waku-vanilla-extract

1. pnpm install
2. pnpm dev
3. open `http://localhost:3000/`
4. you can see this and check out your console error:

![스크린샷 2024-10-06 16 49 26](https://github.com/user-attachments/assets/07e04a1a-b9ad-4ecb-837f-3f8f2064fb47)

## Additional Contexts

- This issue is only on Dev mode(`pnpm dev`). I tried to do `pnpm build` and `pnpm start`, but there were no issues.
- I've investigated for this issue
  - `__vanilla_globalCssAdapter__` you can see is [used `@vanilla-extract/vite-plugin` internally.](https://github.com/vanilla-extract-css/vanilla-extract/blob/284098c02dcfb85026dab1dbe29563301095530a/packages/integration/src/compiler.ts#L18) Bug I don't know what it is. 😅

**Comment by dai-shi** [comment]
Is #750 somehow related?

**Comment by ojj1123** [comment]
My issue also work well when using client component.

**Comment by ojj1123** [comment]
It could be upstream issue.

Btw, What is `rsc-delegate-plugin`?

**Comment by dai-shi** [comment]
I think you've asked it before, but anyway, it's a way to bridge our two vite servers for delegating hot reloads.

**Comment by ojj1123** [comment]
I'm investigating to resolve this issue, but I'm gonna take some time 😅
I guess waku doesn't deal with outputs of `@vanilla-extract/vite-plugin`. And I found something:

```diff
-import { container } from "../components/styles.css"
+import { container } from "../components/styles.css.js"
```

**When I did like this, It has no error but there are no styles at all.(including tailwindcss).** It means no css files are being injected to html on dev mode.

**Comment by kulkarnisaumitra98** [comment]
@dai-shi  I think the root cause of issue is the [configFile: false](https://github.com/dai-shi/waku/blob/8bacd5df1ba0c42fa4f1ed0e7d53ab0c409c3374/packages/waku/src/lib/utils/merge-vite-config.ts#L28) attribute. We are passing it because we resolve the vite config by calling the resolveConfig function, which causes unexpeceted issues.  If I am not wrong we don't need to call it as it is internally called by the [createViteServer](https://github.com/vitejs/vite/blob/1bfe21b9440f318c940f90e425a18588595225fd/packages/vite/src/node/server/index.ts#L435) anyways. 

Since we pass configFile as false, the vanillaExtract plugin [honours that attribute](https://github.com/vanilla-extract-css/vanilla-extract/blob/28df959c1d407c0ae03b8dc2d5363de60513d4ff/packages/vite-plugin/src/index.ts#L128-L143) and passes waku vite server's inlineConfig to it's [own viteServer instance](https://github.com/vanilla-extract-css/vanilla-extract/blob/28df959c1d407c0ae03b8dc2d5363de60513d4ff/packages/integration/src/compiler.ts#L58-L103), which causes all of our plugins to run. And in the rscHmrPlugin where we create html, the vite server instance gets changed, which ultimately fails the generation of css.

I have added the possible solution [here](https://github.com/dai-shi/waku/pull/1036), please have a look.

**Comment by dai-shi** [comment]
Thanks for looking into it.
For the suggestion, I think we need to ask @Aslemammad for some insights.

**Comment by Aslemammad** [comment]
> If I am not wrong we don't need to call it as it is internally called by the [createViteServer](https://github.com/vitejs/vite/blob/1bfe21b9440f318c940f90e425a18588595225fd/packages/vite/src/node/server/index.ts#L435) anyways.

if that's true, we can remove the mergeConfig! but that need to be verified so we do not lose the support of vite configs.

**Comment by dai-shi** [comment]
> the vanillaExtract plugin [honours that attribute](https://github.com/vanilla-extract-css/vanilla-extract/blob/28df959c1d407c0ae03b8dc2d5363de60513d4ff/packages/vite-plugin/src/index.ts#L128-L143) and passes waku vite server's inlineConfig

That's a very unexpected usage of the attribute, but can't blame. Let's hope #1036 works.
